package tc.data.test;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tc.data.test.Attending;
import tc.data.test.AttendingExample;

public interface AttendingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int countByExample(AttendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByExample(AttendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insert(Attending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insertSelective(Attending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<Attending> selectByExample(AttendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    Attending selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") Attending record, @Param("example") AttendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExample(@Param("record") Attending record, @Param("example") AttendingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeySelective(Attending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attending
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKey(Attending record);
}