package tc.data.test;

import java.util.Date;

public class Attending {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.ismemeber
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer ismemeber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attending.score
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.id
     *
     * @return the value of attending.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.id
     *
     * @param id the value for attending.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.sid
     *
     * @return the value of attending.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.sid
     *
     * @param sid the value for attending.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.cid
     *
     * @return the value of attending.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.cid
     *
     * @param cid the value for attending.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.state
     *
     * @return the value of attending.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.state
     *
     * @param state the value for attending.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.ismemeber
     *
     * @return the value of attending.ismemeber
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getIsmemeber() {
        return ismemeber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.ismemeber
     *
     * @param ismemeber the value for attending.ismemeber
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setIsmemeber(Integer ismemeber) {
        this.ismemeber = ismemeber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.time
     *
     * @return the value of attending.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.time
     *
     * @param time the value for attending.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attending.score
     *
     * @return the value of attending.score
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attending.score
     *
     * @param score the value for attending.score
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }
}