package tc.data.test;

public class Bankcard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.balance
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Double balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.id
     *
     * @return the value of bankcard.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.id
     *
     * @param id the value for bankcard.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.balance
     *
     * @return the value of bankcard.balance
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.balance
     *
     * @param balance the value for bankcard.balance
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }
}