package tc.data.test;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.insid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.startdate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.enddate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.agree
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer agree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.insid
     *
     * @return the value of course.insid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.insid
     *
     * @param insid the value for course.insid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setInsid(Long insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tid
     *
     * @return the value of course.tid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tid
     *
     * @param tid the value for course.tid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.startdate
     *
     * @return the value of course.startdate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.startdate
     *
     * @param startdate the value for course.startdate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.enddate
     *
     * @return the value of course.enddate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.enddate
     *
     * @param enddate the value for course.enddate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.agree
     *
     * @return the value of course.agree
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.agree
     *
     * @param agree the value for course.agree
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setAgree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}