package tc.data.test;

import java.util.Date;

public class Fundlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.type
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.sum
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Double sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.id
     *
     * @return the value of fundlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.id
     *
     * @param id the value for fundlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.type
     *
     * @return the value of fundlog.type
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.type
     *
     * @param type the value for fundlog.type
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.state
     *
     * @return the value of fundlog.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.state
     *
     * @param state the value for fundlog.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.cid
     *
     * @return the value of fundlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.cid
     *
     * @param cid the value for fundlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.sid
     *
     * @return the value of fundlog.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.sid
     *
     * @param sid the value for fundlog.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.sum
     *
     * @return the value of fundlog.sum
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Double getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.sum
     *
     * @param sum the value for fundlog.sum
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setSum(Double sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundlog.time
     *
     * @return the value of fundlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundlog.time
     *
     * @param time the value for fundlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}