package tc.data.test;

import java.util.Date;

public class Institutionlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institutionlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institutionlog.insid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institutionlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institutionlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institutionlog.id
     *
     * @return the value of institutionlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institutionlog.id
     *
     * @param id the value for institutionlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institutionlog.insid
     *
     * @return the value of institutionlog.insid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institutionlog.insid
     *
     * @param insid the value for institutionlog.insid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setInsid(Long insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institutionlog.cid
     *
     * @return the value of institutionlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institutionlog.cid
     *
     * @param cid the value for institutionlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institutionlog.time
     *
     * @return the value of institutionlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institutionlog.time
     *
     * @param time the value for institutionlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}