package tc.data.test;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tc.data.test.Institutionlog;
import tc.data.test.InstitutionlogExample;
import tc.data.test.InstitutionlogWithBLOBs;

public interface InstitutionlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int countByExample(InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByExample(InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insert(InstitutionlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insertSelective(InstitutionlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<InstitutionlogWithBLOBs> selectByExampleWithBLOBs(InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<Institutionlog> selectByExample(InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    InstitutionlogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") InstitutionlogWithBLOBs record, @Param("example") InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") InstitutionlogWithBLOBs record, @Param("example") InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExample(@Param("record") Institutionlog record, @Param("example") InstitutionlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeySelective(InstitutionlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(InstitutionlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institutionlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKey(Institutionlog record);
}