package tc.data.test;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tc.data.test.Institution;
import tc.data.test.InstitutionExample;
import tc.data.test.InstitutionWithBLOBs;

public interface InstitutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int countByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insert(InstitutionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insertSelective(InstitutionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<InstitutionWithBLOBs> selectByExampleWithBLOBs(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<Institution> selectByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    InstitutionWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") InstitutionWithBLOBs record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") InstitutionWithBLOBs record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExample(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeySelective(InstitutionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(InstitutionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKey(Institution record);
}