package tc.data.test;

import java.util.Date;

public class Membercard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.balance
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.level
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.bankid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long bankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.suspenddate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date suspenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column membercard.destroydate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date destroydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.id
     *
     * @return the value of membercard.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.id
     *
     * @param id the value for membercard.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.balance
     *
     * @return the value of membercard.balance
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.balance
     *
     * @param balance the value for membercard.balance
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.state
     *
     * @return the value of membercard.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.state
     *
     * @param state the value for membercard.state
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.level
     *
     * @return the value of membercard.level
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.level
     *
     * @param level the value for membercard.level
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.bankid
     *
     * @return the value of membercard.bankid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.bankid
     *
     * @param bankid the value for membercard.bankid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setBankid(Long bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.suspenddate
     *
     * @return the value of membercard.suspenddate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getSuspenddate() {
        return suspenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.suspenddate
     *
     * @param suspenddate the value for membercard.suspenddate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setSuspenddate(Date suspenddate) {
        this.suspenddate = suspenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column membercard.destroydate
     *
     * @return the value of membercard.destroydate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getDestroydate() {
        return destroydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column membercard.destroydate
     *
     * @param destroydate the value for membercard.destroydate
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setDestroydate(Date destroydate) {
        this.destroydate = destroydate;
    }
}