package tc.data.test;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tc.data.test.Membercard;
import tc.data.test.MembercardExample;

public interface MembercardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int countByExample(MembercardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByExample(MembercardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insert(Membercard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insertSelective(Membercard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<Membercard> selectByExample(MembercardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    Membercard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") Membercard record, @Param("example") MembercardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExample(@Param("record") Membercard record, @Param("example") MembercardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeySelective(Membercard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table membercard
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKey(Membercard record);
}