package tc.data.test;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tc.data.test.Student;
import tc.data.test.StudentExample;
import tc.data.test.StudentWithBLOBs;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insert(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insertSelective(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<StudentWithBLOBs> selectByExampleWithBLOBs(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    StudentWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") StudentWithBLOBs record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") StudentWithBLOBs record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeySelective(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKey(Student record);
}