package tc.data.test;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bankid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long bankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.memeberid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long memeberid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bankid
     *
     * @return the value of student.bankid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bankid
     *
     * @param bankid the value for student.bankid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setBankid(Long bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.memeberid
     *
     * @return the value of student.memeberid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getMemeberid() {
        return memeberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.memeberid
     *
     * @param memeberid the value for student.memeberid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setMemeberid(Long memeberid) {
        this.memeberid = memeberid;
    }
}