package tc.data.test;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tc.data.test.Studentlog;
import tc.data.test.StudentlogExample;
import tc.data.test.StudentlogWithBLOBs;

public interface StudentlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int countByExample(StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByExample(StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insert(StudentlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int insertSelective(StudentlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<StudentlogWithBLOBs> selectByExampleWithBLOBs(StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    List<Studentlog> selectByExample(StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    StudentlogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") StudentlogWithBLOBs record, @Param("example") StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") StudentlogWithBLOBs record, @Param("example") StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByExample(@Param("record") Studentlog record, @Param("example") StudentlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeySelective(StudentlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(StudentlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentlog
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    int updateByPrimaryKey(Studentlog record);
}