package tc.data.test;

import java.util.Date;

public class Studentlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlog.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlog.id
     *
     * @return the value of studentlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlog.id
     *
     * @param id the value for studentlog.id
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlog.sid
     *
     * @return the value of studentlog.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlog.sid
     *
     * @param sid the value for studentlog.sid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlog.cid
     *
     * @return the value of studentlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlog.cid
     *
     * @param cid the value for studentlog.cid
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlog.time
     *
     * @return the value of studentlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlog.time
     *
     * @param time the value for studentlog.time
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}