package tc.data.test;

public class StudentlogWithBLOBs extends Studentlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlog.behavior
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private String behavior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentlog.description
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlog.behavior
     *
     * @return the value of studentlog.behavior
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlog.behavior
     *
     * @param behavior the value for studentlog.behavior
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentlog.description
     *
     * @return the value of studentlog.description
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentlog.description
     *
     * @param description the value for studentlog.description
     *
     * @mbggenerated Sat Feb 25 15:12:43 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}